In [1]:
import pandas as pd

In [10]:
dataframe1 = pd.DataFrame(
    {
        'Fiat': ['Palio', 'Uno', '147', 'Argos'],
        'Chevrolet': ['Kadet', 'Celta', 'Meriva', 'Onix'],
        'VolksWagen': ['Gol', 'Saveiro', 'T-Cross', 'Virtus'],
        'Ford': ['Ka', 'Fiesta', 'Focus', 'EcoSport'],
     
    }, 
      index=[0,1,2,3],
)

dataframe2 = pd.DataFrame(
    {
        'Fiat': ['Punto', 'Premium', 'Siena', 'Weekend'],
        'Chevrolet': ['Camaro', 'Cruze', 'Equinox', 'Tracker'],
        'VolksWagen': ['Santana', 'Parati', 'Golf', 'Polo'],
        'Ford': ['Ranger', 'Maverick', 'Escort', 'Del Ray'],
     
    }, 
      index=[4,5,6,7],
)

In [11]:
dataframe1.head()

    Fiat Chevrolet VolksWagen      Ford
0  Palio     Kadet        Gol        Ka
1    Uno     Celta    Saveiro    Fiesta
2    147    Meriva    T-Cross     Focus
3  Argos      Onix     Virtus  EcoSport

In [5]:
dataframe1.shape

(4, 4)

In [12]:
dataframe2.head()

      Fiat Chevrolet VolksWagen      Ford
4    Punto    Camaro    Santana    Ranger
5  Premium     Cruze     Parati  Maverick
6    Siena   Equinox       Golf    Escort
7  Weekend   Tracker       Polo   Del Ray

In [7]:
dataframe2.shape

(4, 4)

In [13]:
dataframe_Final = pd.concat([dataframe1,dataframe2])

In [14]:
dataframe_Final.head()

    Fiat Chevrolet VolksWagen      Ford
0  Palio     Kadet        Gol        Ka
1    Uno     Celta    Saveiro    Fiesta
2    147    Meriva    T-Cross     Focus
3  Argos      Onix     Virtus  EcoSport
4  Punto    Camaro    Santana    Ranger

In [21]:
datafram1 = pd.DataFrame(
    {
        'Fiat': ['Palio', 'Uno', '147', 'Argos'],
        'Chevrolet': ['Kadet', 'Celta', 'Meriva', 'Onix'],
        'VolksWagen': ['Gol', 'Saveiro', 'T-Cross', 'Virtus'],
        'Ford': ['Ka', 'Fiesta', 'Focus', 'EcoSport'],
     
    }, 
      index=[0,1,2,3],
)

dataframe3 = pd.DataFrame(
    {
        'Peugeout': ['208', '308', '307', '2008'],
        'Citroen': ['C3', 'C4', 'DS3', 'AirCross'],
        'Toyota': ['Corolla', 'Yaris', 'RAV4', 'SW4'],
        'Renault': ['Duster', 'Logan', 'Kwid', 'Sandero'],
     
    }, 
      index=[2,3,4,5],
)

In [26]:
dataframe_Final2 = pd.concat([dataframe1,dataframe3], axis=1, join='outer')

In [27]:
dataframe_Final2.head()

    Fiat Chevrolet VolksWagen      Ford Peugeout Citroen   Toyota Renault
0  Palio     Kadet        Gol        Ka      NaN     NaN      NaN     NaN
1    Uno     Celta    Saveiro    Fiesta      NaN     NaN      NaN     NaN
2    147    Meriva    T-Cross     Focus      208      C3  Corolla  Duster
3  Argos      Onix     Virtus  EcoSport      308      C4    Yaris   Logan
4    NaN       NaN        NaN       NaN      307     DS3     RAV4    Kwid

In [25]:
dataframe_Final3 = pd.concat([dataframe1,dataframe3], axis=1, join='inner')

In [28]:
dataframe_Final3.head()

    Fiat Chevrolet VolksWagen      Ford Peugeout Citroen   Toyota Renault
2    147    Meriva    T-Cross     Focus      208      C3  Corolla  Duster
3  Argos      Onix     Virtus  EcoSport      308      C4    Yaris   Logan